# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - if [[ "$OSTYPE" != "linux-gnu" ]]; then sudo tlmgr install framed titling; fi
os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel


after_success:
  - Rscript -e 'covr::codecov()'
